### ISSUE TITLE
Compile with Centos7, LuaJIT 2.0.4, Nginx sources

### ISSUE THREAD

**Issue by BP9906** [openresty/lua-nginx-module#889]
Getting compiler issues with nginx 1.10.1 and LuaJIT compiling on Centos7.

`/usr/local/source/nginx-1.10.1/../lua-nginx-module//src/ngx_http_lua_ssl_session_storeby.c:513: multiple definition of `ngx_http_lua_ffi_ssl_get_session_id'
objs/addon/src/ngx_http_lua_ssl_session_storeby.o:/usr/local/source/nginx-1.10.1/../lua-nginx-module//src/ngx_http_lua_ssl_session_storeby.c:513: first defined here
objs/addon/src/ngx_http_lua_ssl_session_storeby.o: In function `ngx_http_lua_ffi_ssl_get_session_id_size':
/usr/local/source/nginx-1.10.1/../lua-nginx-module//src/ngx_http_lua_ssl_session_storeby.c:562: multiple definition of `ngx_http_lua_ffi_ssl_get_session_id_size'
objs/addon/src/ngx_http_lua_ssl_session_storeby.o:/usr/local/source/nginx-1.10.1/../lua-nginx-module//src/ngx_http_lua_ssl_session_storeby.c:562: first defined here
objs/addon/src/ngx_http_lua_ssl_session_fetchby.o: In function `ngx_http_lua_ssl_sess_fetch_handler_file':
/usr/local/source/nginx-1.10.1/../lua-nginx-module//src/ngx_http_lua_ssl_session_fetchby.c:39: multiple definition of `ngx_http_lua_ssl_sess_fetch_handler_file'
objs/addon/src/ngx_http_lua_ssl_session_fetchby.o:/usr/local/source/nginx-1.10.1/../lua-nginx-module//src/ngx_http_lua_ssl_session_fetchby.c:39: first defined here
objs/addon/src/ngx_http_lua_ssl_session_fetchby.o: In function `ngx_http_lua_ssl_sess_fetch_by_lua':
/usr/local/source/nginx-1.10.1/../lua-nginx-module//src/ngx_http_lua_ssl_session_fetchby.c:111: multiple definition of `ngx_http_lua_ssl_sess_fetch_by_lua'
objs/addon/src/ngx_http_lua_ssl_session_fetchby.o:/usr/local/source/nginx-1.10.1/../lua-nginx-module//src/ngx_http_lua_ssl_session_fetchby.c:111: first defined here
objs/addon/src/ngx_http_lua_ssl_session_fetchby.o: In function `ngx_http_lua_ssl_sess_fetch_handler_inline':
/usr/local/source/nginx-1.10.1/../lua-nginx-module//src/ngx_http_lua_ssl_session_fetchby.c:60: multiple definition of `ngx_http_lua_ssl_sess_fetch_handler_inline'
objs/addon/src/ngx_http_lua_ssl_session_fetchby.o:/usr/local/source/nginx-1.10.1/../lua-nginx-module//src/ngx_http_lua_ssl_session_fetchby.c:60: first defined here
objs/addon/src/ngx_http_lua_ssl_session_fetchby.o: In function `ngx_http_lua_ssl_sess_fetch_by_lua_block':
/usr/local/source/nginx-1.10.1/../lua-nginx-module//src/ngx_http_lua_ssl_session_fetchby.c:82: multiple definition of `ngx_http_lua_ssl_sess_fetch_by_lua_block'
objs/addon/src/ngx_http_lua_ssl_session_fetchby.o:/usr/local/source/nginx-1.10.1/../lua-nginx-module//src/ngx_http_lua_ssl_session_fetchby.c:82: first defined here
objs/addon/src/ngx_http_lua_ssl_session_fetchby.o: In function `ngx_http_lua_ssl_sess_fetch_handler':
/usr/local/source/nginx-1.10.1/../lua-nginx-module//src/ngx_http_lua_ssl_session_fetchby.c:176: multiple definition of `ngx_http_lua_ssl_sess_fetch_handler'
objs/addon/src/ngx_http_lua_ssl_session_fetchby.o:/usr/local/source/nginx-1.10.1/../lua-nginx-module//src/ngx_http_lua_ssl_session_fetchby.c:176: first defined here
objs/addon/src/ngx_http_lua_ssl_session_fetchby.o: In function `ngx_http_lua_ffi_ssl_set_serialized_session':
/usr/local/source/nginx-1.10.1/../lua-nginx-module//src/ngx_http_lua_ssl_session_fetchby.c:548: multiple definition of `ngx_http_lua_ffi_ssl_set_serialized_session'
objs/addon/src/ngx_http_lua_ssl_session_fetchby.o:/usr/local/source/nginx-1.10.1/../lua-nginx-module//src/ngx_http_lua_ssl_session_fetchby.c:548: first defined here
objs/addon/src/ngx_http_lua_ssl.o: In function `ngx_http_lua_ssl_init':
/usr/local/source/nginx-1.10.1/../lua-nginx-module//src/ngx_http_lua_ssl.c:22: multiple definition of `ngx_http_lua_ssl_init'
objs/addon/src/ngx_http_lua_ssl.o:/usr/local/source/nginx-1.10.1/../lua-nginx-module//src/ngx_http_lua_ssl.c:22: first defined here
objs/addon/src/ngx_http_lua_ssl.o:(.data+0x0): multiple definition of `ngx_http_lua_ssl_ctx_index'
objs/addon/src/ngx_http_lua_ssl.o:(.data+0x0): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory `/usr/local/source/nginx-1.10.1'
make: *** [build] Error 2
`

Compile options (Centos' compile options plus added modules):

`./configure --add-module=../lua-nginx-module/ --add-module=../naxsi-master/naxsi_src/ --add-module=../nginx-auth-ldap/ --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/var/run/nginx.pid --lock-path=/var/lock/subsys/nginx --user=nginx --group=nginx --with-http_gunzip_module --with-http_auth_request_module --with-file-aio --with-ipv6 --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module --with-http_image_filter_module --with-http_geoip_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_stub_status_module --with-http_perl_module --with-mail --with-mail_ssl_module --with-debug --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic' --with-ld-opt="-Wl,-E,-rpath,/usr/local/lib/"
`

**Comment by agentzh** [comment]
@BP9906 Please use the latest OpenResty release instead:

https://openresty.org/en/download.html

**Comment by BP9906** [comment]
Tried it, same error.

`objs/addon/src/ngx_http_rds_csv_output.o:/home/source/openresty-1.11.2.1/build/nginx-1.11.2/../rds-csv-nginx-module-0.07/src/ngx_http_rds_csv_output.c:217: first defined here
objs/addon/src/ngx_http_rds_csv_output.o: In function `ngx_http_rds_csv_output_field':
/home/source/openresty-1.11.2.1/build/nginx-1.11.2/../rds-csv-nginx-module-0.07/src/ngx_http_rds_csv_output.c:303: multiple definition of `ngx_http_rds_csv_output_field'
objs/addon/src/ngx_http_rds_csv_output.o:/home/source/openresty-1.11.2.1/build/nginx-1.11.2/../rds-csv-nginx-module-0.07/src/ngx_http_rds_csv_output.c:303: first defined here
objs/addon/src/ngx_http_rds_csv_output.o: In function `ngx_http_rds_csv_output_more_field_data':
/home/source/openresty-1.11.2.1/build/nginx-1.11.2/../rds-csv-nginx-module-0.07/src/ngx_http_rds_csv_output.c:468: multiple definition of `ngx_http_rds_csv_output_more_field_data'
objs/addon/src/ngx_http_rds_csv_output.o:/home/source/openresty-1.11.2.1/build/nginx-1.11.2/../rds-csv-nginx-module-0.07/src/ngx_http_rds_csv_output.c:468: first defined here
collect2: error: ld returned 1 exit status
gmake[2]: *** [objs/nginx] Error 1
gmake[2]: Leaving directory `/home/source/openresty-1.11.2.1/build/nginx-1.11.2'
gmake[1]: *** [build] Error 2
gmake[1]: Leaving directory `/home/source/openresty-1.11.2.1/build/nginx-1.11.2'
gmake: *** [all] Error 2`

**Comment by BP9906** [comment]
I found another bug item where someone reported the issue was with Naxsi.  I've since downloaded the latest Naxsi and re-built w/o openresty and just the modules required for LUA and it compiled successfully.

**Comment by agentzh** [comment]
@BP9906 Yes, I was about to say it was a known bug in Naxsi's build system, not our concerns.
