### ISSUE TITLE
Does not compile on nginx >= 1.11.11

### ISSUE THREAD

**Issue by Stono** [openresty/lua-nginx-module#1051]
Hello!
I get the following error when trying to compile lua-nginx-module version 0.10.8 the module against nginx >= 1.11.11, it works fine on 1.11.10.

I wasn't sure if I should raise this issue here, or with the nginx team.

You can recreate this by cloning my repo: https://github.com/Stono/docker-nginx-letsencrypt and changing NGINX_VERSION from 1.11.10 to 1.11.11 or above.

```
/usr/local/src/lua-nginx-module/src/ngx_http_lua_headers.c: In function 'ngx_http_lua_ngx_req_raw_header':
/usr/local/src/lua-nginx-module/src/ngx_http_lua_headers.c:151:15: error: incompatible types when assigning to type 'struct ngx_buf_t *' from type 'ngx_chain_t'
             b = hc->busy[i];
               ^
/usr/local/src/lua-nginx-module/src/ngx_http_lua_headers.c:227:15: error: incompatible types when assigning to type 'struct ngx_buf_t *' from type 'ngx_chain_t'
             b = hc->busy[i];
               ^
make[1]: *** [objs/addon/src/ngx_http_lua_headers.o] Error 1
```

Thanks 
Karl

**Comment by agentzh** [comment]
@Stono Use the master branch.
