### ISSUE TITLE
build error with nginx 1.7.4 or older version

### ISSUE THREAD

**Issue by timebug** [openresty/lua-nginx-module#1779]
Hello!

When I upgrade lua-nginx-module form v0.10.13 to v0.10.14 (or newer version) with Nginx 1.7.4, it build failed:

```
lua-nginx-module-0.10.14/src/ngx_http_lua_socket_tcp.c: In function 'ngx_http_lua_tcp_queue_conn_op_cleanup':
lua-nginx-module-0.10.14/src/ngx_http_lua_socket_tcp.c:6053:27: error: 'ngx_event_t' has no member named 'posted'
     if (conn_op_ctx->event.posted) {
                           ^
```

I found https://github.com/openresty/lua-nginx-module/commit/761ddca72deb4595ff93df7840dfa39854126123 this pull request added this part of the code, but Nginx include `event.posted` util 1.7.5 version, see https://github.com/nginx/nginx/commit/37d24e7e3be648a6f73bad18dcf53798a7a1aeb0. Considering that the 1.7.x series is still supported, do something compatible here?
