### ISSUE TITLE
Module Does Not Compile with LibreSSL 3.0+

### ISSUE THREAD

**Issue by Firegarden** [openresty/lua-nginx-module#1833]
Compile error - can not get nginx to compile due to this error. 

ngx_http_lua_ssl_certby.c:1452:13: error: implicit declaration of function ‘SSL_set0_verify_cert_store’; did you mean ‘SSL_set_verify_result’?

It seems lua-nginx-module-0.10.19 is not building with LibreSSL. I have tried LibreSSL 3.2 and LibreSSL 3.3. This issue is new to 0.10.19 and does not occur if I drop back to lua-nginx-module-0.10.17 with LibreSSL

some basic info from my compile script

LUA_JIT_VER=2.1-20201027
LUA_NGINX_VER=0.10.19
LUA_RESTY_CORE=0.1.21
LIBRESSL_VER=3.3.0
NGINX_MAINLINE_VER=1.19.5
NGINX_DEV_KIT=0.3.1 

It seems there is no function definition found - maybe the order of declaration? I am not a C programmer so I don't understand the error. Some stack trace below.
`cc -c -I/usr/local/include/luajit-2.1/  -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -Wno-ignored-qualifiers  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-deprecated-declarations -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/src/nginx/modules/ngx_devel_kit-0.3.1/objs -I objs/addon/ndk -I /usr/local/src/nginx/modules/lua-nginx-module-0.10.19/src/api -I /usr/local/src/nginx/modules/libressl-3.3.0/.openssl/include -I obj
        -o objs/addon/src/ngx_http_lua_ssl_ocsp.o \
        /usr/local/src/nginx/modules/lua-nginx-module-0.10.19/src/ngx_http_lua_ssl_ocsp.c
/usr/local/src/nginx/modules/lua-nginx-module-0.10.19/src/ngx_http_lua_ssl_certby.c: In function ‘ngx_http_lua_ffi_ssl_verify_client’:
/usr/local/src/nginx/modules/lua-nginx-module-0.10.19/src/ngx_http_lua_ssl_certby.c:1452:13: error: implicit declaration of function ‘SSL_set0_verify_cert_store’; did you mean ‘SSL_set_verify_result’? [-Werror=implicit-function-declaration]
 1452 |         if (SSL_set0_verify_cert_store(ssl_conn, ca_store) == 0) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |             SSL_set_verify_result
cc -c -I/usr/local/include/luajit-2.1/  -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -Wno-ignored-qualifiers  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-deprecated-declarations -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/src/nginx/modules/ngx_devel_kit-0.3.1/objs -I objs/addon/ndk -I /usr/local/src/nginx/modules/lua-nginx-module-0.10.19/src/api -I /usr/local/src/nginx/modules/libressl-3.3.0/.openssl/include -I obj>
        -o objs/addon/src/ngx_http_lua_lex.o \
        /usr/local/src/nginx/modules/lua-nginx-module-0.10.19/src/ngx_http_lua_lex.c
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:2238: objs/addon/src/ngx_http_lua_ssl_certby.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/usr/local/src/nginx/nginx-1.19.5'
make: *** [Makefile:8: build] Error 2
`

**Comment by Firegarden** [comment]
I tested my compile script with OpenSSL 1.1.1h and it compiles fine and so this compile issue is specific to LIbreSSL

**Comment by jprjr** [comment]
Just wanted to add I ran into this same issue.

https://github.com/openresty/lua-nginx-module/blob/7105adaa523adedec80f0aaa13388b88d08988f8/src/ngx_http_lua_ssl_certby.c#L1452

Tested with both LibreSSL 3.2.2 (latest stable release) and LibreSSL 3.3.0 (latest development release). As far as I can tell LibreSSL does not support these functions, I suspect these need to be macro'd out via `#ifdef LIBRESSL_VERSION_NUMBER`

**Comment by chartera** [comment]
`#ifndef LIBRESSL_VERSION_TEXT                                                                                                                         
        if (SSL_set0_verify_cert_store(ssl_conn, ca_store) == 0) { // ... }                                                                                                                                                     
        #endif`
should does it

**Comment by Firegarden** [comment]
Ping. LibreSSL users are still limited to working with version 0.1.17 on Ubuntu 20.04 with latest NGINX 1.19.10 in order to compile NGINX from source.

I am wondering if this could get some attention? 

Again problem is that a fresh server install will not build NGINX 1.19.X from source on Ubuntu 20.04 with LibreSSL 3.3 and the lua-nginx-module higher than 0.10.17

I have not yet tried  v0.10.20rc1 but will asap

**Comment by Firegarden** [comment]
I do not understand how you can consider this a "FEATURE?" What is the alternative SSL library to use? Please help me understand what other SSL library you suggest?

**Comment by spacewander** [comment]
Well, OpenSSL is the default SSL library. So support another SSL library is a feature.

**Comment by Firegarden** [comment]
I was afraid you would say that. Thank you for your answer. Don't you feel the user base of this module is significantly limited by only supporting Open SSL given the importance of TLS and the considerable improvements that LibreSSL brings to the table?

**Comment by jprjr** [comment]
When LibreSSL was first created it was great, but it seems to be lagging behind OpenSSL. Some of the Linux distros that adopted it as their default SSL library have started dropping it and switching back to OpenSSL. Here's announcements from [Gentoo](https://www.gentoo.org/support/news-items/2021-01-05-libressl-support-discontinued.html), [Void Linux](https://voidlinux.org/news/2021/02/OpenSSL.html), and [Alpine Linux](https://alpinelinux.org/posts/Alpine-3.9.0-released.html).

I'm not sure what improvements it has over OpenSSL nowadays, if any. That's not to say it doesn't have advantages over OpenSSL - I honestly don't know.

Do you have a list of the improvements/advantages it offers over OpenSSL? That would probably help with determining how much support to offer for LibreSSL as an alternative TLS implementation.

**Comment by Firegarden** [comment]
You are wise sir! I have reviewed in a few places and OpenSSL does appear to be little ahead nowadays especially with QUIC support. Thank you!
