### ISSUE TITLE
Nginx 1.11.11 Compilation Error

### ISSUE THREAD

**Issue by charlesportwoodii** [openresty/lua-nginx-module#1016]
Hi again,

The Lua module fails to compile with Nginx 1.11.11. Just wanted to get this on the radar.

### Compilation Error
```bash
modules/lua-nginx-module/src/ngx_http_lua_headers.c: In function ‘ngx_http_lua_ngx_req_raw_header’:
modules/lua-nginx-module/src/ngx_http_lua_headers.c:145:15: error: incompatible types when assigning to type ‘ngx_buf_t * {aka struct ngx_buf_s *}’ from type ‘ngx_chain_t {aka struct ngx_chain_s}’
             b = hc->busy[i];
               ^
modules/lua-nginx-module/src/ngx_http_lua_headers.c:221:15: error: incompatible types when assigning to type ‘ngx_buf_t * {aka struct ngx_buf_s *}’ from type ‘ngx_chain_t {aka struct ngx_chain_s}’
             b = hc->busy[i];
               ^
objs/Makefile:1935: recipe for target 'objs/addon/src/ngx_http_lua_headers.o' failed
make[1]: *** [objs/addon/src/ngx_http_lua_headers.o] Error 1
make[1]: Leaving directory '/tmp/nginx-1.11.11'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
```

### Versions
Nginx: 1.11.11
Lua Module: v0.10.7

### Related Issues:
Related: https://github.com/openresty/echo-nginx-module/issues/64

### Notes

>     *) Bugfix: a segmentation fault might occur in a worker process if
>       number of large_client_header_buffers in a virtual server was
>       different from the one in the default server.

This appears to be the offending commit: https://github.com/nginx/nginx/commit/fca26c2e53d46549320a3b23ce0398c5921348dd

**Comment by agentzh** [comment]
@charlesportwoodii Patches welcome.

**Comment by charlesportwoodii** [comment]
@agentzh I know. =) I was looking at creating a patch earlier today but got hung up on other things. Not sure if I'm going to be able to get to creating a patch this week or not. I'll submit a PR if I can get some time this week to take a deeper look at it.

**Comment by defanator** [comment]
@charlesportwoodii, @agentzh - I've just submitted PR #1017 that fixes the build. I also did a simple check with `ngx.req.raw_header()` and it seems to work.

**Comment by neilstuartcraig** [comment]
FWIW i just hit the same issue. Once the fix is available i'll test/confirm too

**Comment by Schamschula** [comment]
Same here, while trying to upgrade nginx for MacPorts.

**Comment by rob-pajak-eagleeye** [comment]
I hit the same issue with Nginx 1.11.12

**Comment by Schamschula** [comment]
I combined the two patches:

https://github.com/macports/macports-ports/blob/master/www/nginx/files/patch-src-ngx_http_lua_headers.c.diff

It works for both 1.11.11 and 1.11.12.

**Comment by kn007** [comment]
Same issue here with nginx 1.11.12.

**Comment by LuckySB** [comment]
senk
with https://github.com/macports/macports-ports/blob/master/www/nginx/files/patch-src-ngx_http_lua_headers.c.diff

module compiled without problem

**Comment by sunjun0000** [comment]
I modified it myself, fixed the error.
Can be downloaded to my personal git repository 
[https://git.sunsblog.cn/sunjun/echo-nginx-module](https://git.sunsblog.cn/sunjun/echo-nginx-module)
[https://git.sunsblog.cn/sunjun/lua-nginx-module ](https://git.sunsblog.cn/sunjun/lua-nginx-module )

**Comment by petrmalkov** [comment]
Same issue here with nginx 1.11.13

**Comment by agentzh** [comment]
Well, just follow the progress in PR #1017. @defanator is still working on it :)

**Comment by lj2007331** [comment]
Same issue here with nginx 1.12.0-stable

**Comment by winstonk** [comment]
Same issue here. For me the issue surfaced in nginx 1.11.11 and up, and today it continues with 1.12.0.

My output in case it's helpful:

```
/src/build/modules/lua/src/ngx_http_lua_headers.c: In function 'ngx_http_lua_ngx_req_raw_header':
/src/build/modules/lua/src/ngx_http_lua_headers.c:151:15: error: incompatible types when assigning to type 'struct ngx_buf_t *' from type 'ngx_chain_t'
             b = hc->busy[i];
               ^
/src/build/modules/lua/src/ngx_http_lua_headers.c:227:15: error: incompatible types when assigning to type 'struct ngx_buf_t *' from type 'ngx_chain_t'
             b = hc->busy[i];
               ^
objs/Makefile:1648: recipe for target 'objs/addon/src/ngx_http_lua_headers.o' failed
make[1]: Leaving directory '/src/build/nginx-1.12.0'
make[1]: *** [objs/addon/src/ngx_http_lua_headers.o] Error 1
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by ljubomirb** [comment]
Nginx 1.13.2, same issue.

**Comment by agentzh** [comment]
@ljubomirb Are you using the latest git master of this module? I believe this is already fixed in master.

**Comment by agentzh** [comment]
@ljubomirb This is also why this issue was closed on April 13.

**Comment by ljubomirb** [comment]
You might be right. So how i came to this place:
while compiling nginx for LEDE project, one ends up with abovementioned error.
The problem is _Makefile_ that obviously points to old version of this git (although I cant't tell wich).
So, for those who come here because of that error, change version part in LEDE nginx makefile to newer. Like this for example:
```
define Download/lua-nginx
	#VERSION:=1967998b0eedab1ff51bff8fafa5fc3db47976aa
    VERSION:=20d6558b074f1bda3584827412f2e364aeb00b0f
	SUBDIR:=lua-nginx
	FILE:=lua-nginx-module-$(PKG_VERSION)-$$(VERSION).tar.gz
	URL:=https://github.com/openresty/lua-nginx-module.git
	PROTO:=git
endef
```
I'll also write this to the maintainer of that file.
Thanks for response!

**Comment by hepking** [comment]
还是有这问题，编译失败

**Comment by agentzh** [comment]
@hepking Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.

**Comment by startan** [comment]
The compile failed problem persists.

**Comment by agentzh** [comment]
@startan For god's sake, why don't you look at this thread closely? It's already fixed in master. DO NOT REPLY TO THIS CLOSED ISSUE ANY MORE!

**Comment by fabiobergamo** [comment]
good afternoon,
I'm having trouble compiling the module, lua-nginx-module / nginx-audio-track-for-hls-module
I am using Centos7, when giving the ./configure command and adding the path I get this message

configuring additional modules
adding module in / root / nginx-rtmp-vlc
 + ngx_rtmp_module was configured
adding module in /root/lua-nginx-module-0.10.12rc2
checking for Lua library ... not found
checking for Lua library in / usr / local / ... not found
checking for Lua library in / usr / local / ... not found
checking for Lua library in / usr / pkg / ... not found
checking for Lua library in / opt / local / ... not found
checking for Lua library in / usr / local / * / lua51 / ... not found
checking for Lua library in / usr / ... not found
checking for LuaJIT library in / usr / local / ... found
checking for export symbols by default (-E) ... found
checking for export symbols by default (--export-all-symbols) ... not found
found for SO_PASSCRED ... found
found for __attribute __ (constructor) ... found
found for malloc_trim ... found
 + ngx_http_lua_module was configured
adding module in / root / nginx-audio-track-for-hls-module
 + ngx_http_aac_module was configured
found for PCRE library ... found
found for PCRE JIT support ... found
found for openSSL library found
found for zlib library found
creating objs / Makefile
____________________________________________

with the make command
-o objs / addon / nginx-audio-track-for-hls-module / ngx_http_aac_module.
        /root/nginx-audio-track-for-hls-module/ngx_http_aac_module.c
/root/nginx-audio-track-for-hls-module/ngx_http_aac_module.c: In function ângx_http_aac_extract_audioâ:
/root/nginx-audio-track-for-hls-module/ngx_http_aac_module.c:210:5: error: âavcodec_copy_contextâ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4098) [-Werror = deprecated-declarations]
     avcodec_copy_context (output_audio_stream-> codec, input_audio_stream-> codec);
     ^
/root/nginx-audio-track-for-hls-module/ngx_http_aac_module.c:210:5: error: âcodecâ is deprecated (declared at /usr/local/include/libavformat/avformat.h:876) [-Werror = deprecated-declarations]
/root/nginx-audio-track-for-hls-module/ngx_http_aac_module.c:210:5: error: âcodecâ is deprecated (declared at /usr/local/include/libavformat/avformat.h:876) [-Werror = deprecated-declarations]
/root/nginx-audio-track-for-hls-module/ngx_http_aac_module.c:223:13: error: âav_free_packetâ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4336) [-Werror = deprecated-declarations]
             av_free_packet (& new_packet);
             ^
/root/nginx-audio-track-for-hls-module/ngx_http_aac_module.c:225:9: error: âav_free_packetâ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4336) [-Werror = deprecated-declarations]
         av_free_packet (& packet);
         ^
/root/nginx-audio-track-for-hls-module/ngx_http_aac_module.c:211:26: error: ignoring return value of âavformat_write_headerâ, declared with attribute warn_unused_result [-Werror = unused-result]
     avformat_write_header (output_format_context, NULL);
                          ^
cc1: all warnings being treated as errors
make [1]: ** [objs / addon / nginx-audio-track-for-hls-module / ngx_http_aac_module.o] Error 1
make [1]: Exiting the directory `/root/nginx-1.13.8 '
make: ** [build] Error 2

**Comment by spacewander** [comment]
@fabiobergamo 
Your compilation error is neither about Nginx 1.11 nor lua-nginx-module.

> root/nginx-audio-track-for-hls-module/ngx_http_aac_module.c:210:5: error: âavcodec_copy_contextâ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4098) [-Werror = deprecated-declarations]

The error message from the compiler already shows why the nginx-audio-track-for-hls-module could not be compiled.

Please don't hijack this closed issue.

**Comment by fabiobergamo** [comment]
Any solution for avodec obsolete?

**Comment by agentzh** [comment]
@fabiobergamo Please stop spamming this project's repo. As @spacewander said, your issue has nothing to do with this project. If you keep posting, we'll block your github account forever.

**Comment by wanlxp** [comment]
> https://github.com/macports/macports-ports/blob/master/www/nginx/files/patch-src-ngx_http_lua_headers.c.diff

this link can't download
