### PR TITLE
feature: allow to be compiled with LibreSSL 3.0+

### LINKED ISSUE #1833: Module Does Not Compile with LibreSSL 3.0+
Compile error - can not get nginx to compile due to this error. 

ngx_http_lua_ssl_certby.c:1452:13: error: implicit declaration of function ‘SSL_set0_verify_cert_store’; did you mean ‘SSL_set_verify_result’?

It seems lua-nginx-module-0.10.19 is not building with LibreSSL. I have tried LibreSSL 3.2 and LibreSSL 3.3. This issue is new to 0.10.19 and does not occur if I drop back to lua-nginx-module-0.10.17 with LibreSSL

some basic info from my compile script

LUA_JIT_VER=2.1-20201027
LUA_NGINX_VER=0.10.19
LUA_RESTY_CORE=0.1.21
LIBRESSL_VER=3.3.0
NGINX_MAINLINE_VER=1.19.5
NGINX_DEV_KIT=0.3.1 

It seems there is no function definition found - maybe the order of declaration? I am not a C programmer so I don't understand the error. Some stack trace below.
`cc -c -I/usr/local/include/luajit-2.1/  -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -Wno-ignored-qualifiers  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-deprecated-declarations -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/src/nginx/modules/ngx_devel_kit-0.3.1/objs -I objs/addon/ndk -I /usr/local/src/nginx/modules/lua-nginx-module-0.10.19/src/api -I /usr/local/src/nginx/modules/libressl-3.3.0/.openssl/include -I obj
        -o objs/addon/src/ngx_http_lua_ssl_ocsp.o \
        /usr/local/src/nginx/modules/lua-nginx-module-0.10.19/src/ngx_http_lua_ssl_ocsp.c
/usr/local/src/nginx/modules/lua-nginx-module-0.10.19/src/ngx_http_lua_ssl_certby.c: In function ‘ngx_http_lua_ffi_ssl_verify_client’:
/usr/local/src/nginx/modules/lua-nginx-module-0.10.19/src/ngx_http_lua_ssl_certby.c:1452:13: error: implicit declaration of function ‘SSL_set0_verify_cert_store’; did you mean ‘SSL_set_verify_result’? [-Werror=implicit-function-declaration]
 1452 |         if (SSL_set0_verify_cert_store(ssl_conn, ca_store) == 0) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |             SSL_set_verify_result
cc -c -I/usr/local/include/luajit-2.1/  -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -Wno-ignored-qualifiers  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-deprecated-declarations -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/src/nginx/modules/ngx_devel_kit-0.3.1/objs -I objs/addon/ndk -I /usr/local/src/nginx/modules/lua-nginx-module-0.10.19/src/api -I /usr/local/src/nginx/modules/libressl-3.3.0/.openssl/include -I obj>
        -o objs/addon/src/ngx_http_lua_lex.o \
        /usr/local/src/nginx/modules/lua-nginx-module-0.10.19/src/ngx_http_lua_lex.c
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:2238: objs/addon/src/ngx_http_lua_ssl_certby.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/usr/local/src/nginx/nginx-1.19.5'
make: *** [Makefile:8: build] Error 2
`

### PR DESCRIPTION
**Pull request by spacewander**
Fix #1833

I hereby granted the copyright of the changes in this pull request
to the authors of this lua-nginx-module project.

### CODE REVIEW

**Review by doujiang24 — APPROVED** [review]

**Comment by Firegarden** [comment]
Lua Nginx Module Compile error - Passing on these comments to let you know this issue ahem *feature request* still exists 

ngx_http_lua_ssl_certby.c:1452:13: error: implicit declaration of function ‘SSL_set0_verify_cert_store’; did you mean ‘SSL_set_verify_result’?

lua-nginx-module-0.10.20rc1 is not building with LibreSSL. I have tried LibreSSL 3.2 and LibreSSL 3.3. This issue is new to 0.10.19 and does not occur if I drop back to lua-nginx-module-0.10.17 with LibreSSL

It seems there is no function definition found - maybe the order of declaration? 

`cc -c -I/usr/local/include/luajit-2.1/  -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -Wno-ignored-qualifiers  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-deprecated-declarations -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/src/nginx/modules/ngx_devel_kit-0.3.1/objs -I objs/addon/ndk -I /usr/local/src/nginx/modules/lua-nginx-module-0.10.20rc1/src/api -I /usr/local/src/nginx/modules/libressl-3.3.3/.open>
        -o objs/addon/src/ngx_http_lua_ssl_ocsp.o \
        /usr/local/src/nginx/modules/lua-nginx-module-0.10.20rc1/src/ngx_http_lua_ssl_ocsp.c
/usr/local/src/nginx/modules/lua-nginx-module-0.10.20rc1/src/ngx_http_lua_ssl_certby.c: In function ‘ngx_http_lua_ffi_ssl_verify_client’:
/usr/local/src/nginx/modules/lua-nginx-module-0.10.20rc1/src/ngx_http_lua_ssl_certby.c:1452:13: error: implicit declaration of function ‘SSL_set0_verify_cert_store’; did you mean ‘SSL_set_verify_result’? [-Werror=implicit-function-declaration]
 1452 |         if (SSL_set0_verify_cert_store(ssl_conn, ca_store) == 0) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |             SSL_set_verify_result
cc -c -I/usr/local/include/luajit-2.1/  -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -Wno-ignored-qualifiers  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-deprecated-declarations -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/src/nginx/modules/ngx_devel_kit-0.3.1/objs -I objs/addon/ndk -I /usr/local/src/nginx/modules/lua-nginx-module-0.10.20rc1/src/api -I /usr/local/src/nginx/modules/libressl-3.3.3/.open>
        -o objs/addon/src/ngx_http_lua_lex.o \
        /usr/local/src/nginx/modules/lua-nginx-module-0.10.20rc1/src/ngx_http_lua_lex.c
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:2238: objs/addon/src/ngx_http_lua_ssl_certby.o] Error 1`

**Comment by Firegarden** [comment]
I deleted my previous comment - I am sorry I did not understand that a recent declaration was added to the source code and so I re-tested a compile using git clone instead of tag and there is a new error as follows

`ngx_http_lua_ssl_certby.c:1337:1: error: ‘ngx_http_lua_ssl_verify_callback’ defined but not used [-Werror=unused-function]`

Any thoughts on how to get this to compile?

 Thank you. 

Error info as follows:

`cc -c -I/usr/local/include/luajit-2.1/  -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -Wno-ignored-qualifiers  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-deprecated-declarations -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/src/nginx/modules/ngx_devel_kit-0.3.1/objs -I objs/addon/ndk -I /usr/local/src/nginx/modules/lua-nginx-module/src/api -I /usr/local/src/nginx/modules/libressl-3.3.3/.openssl/include -I o>
        -o objs/addon/src/ngx_http_lua_ssl_ocsp.o \
        /usr/local/src/nginx/modules/lua-nginx-module/src/ngx_http_lua_ssl_ocsp.c
/usr/local/src/nginx/modules/lua-nginx-module/src/ngx_http_lua_ssl_certby.c:1337:1: error: ‘ngx_http_lua_ssl_verify_callback’ defined but not used [-Werror=unused-function]
 1337 | ngx_http_lua_ssl_verify_callback(int ok, X509_STORE_CTX *x509_store)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:2238: objs/addon/src/ngx_http_lua_ssl_certby.o] Error 1
`

**Comment by spacewander** [comment]
You can add `#ifdef LIBRESSL_VERSION_NUMBER` to exclude the `ngx_http_lua_ssl_verify_callback` definition. 
PR is welcome!

**Comment by Firegarden** [comment]
Thank you for the feedback. Please that I am border line moron is it possible that you can be more  specific as to how to do this? Am I modifying the source code I pull from github before I compile?

Thank you!

**Comment by Firegarden** [comment]
I deleted my last comment as I am trying the suggestion as follows by editing line 1337 of ngx_http_lua_ssl_certby.c

`#ifdef LIBRESSL_VERSION_NUMBER
static int
ngx_http_lua_ssl_verify_callback(int ok, X509_STORE_CTX *x509_store)
{
    /*
     * we never terminate handshake here and user can later use
     * $ssl_client_verify to check verification result.
     *
     * this is consistent with Nginx behavior.
     */
    return 1;
}
#endif
`

**Comment by Firegarden** [comment]
I am getting the same error when using that #ifdef check 
`ngx_http_lua_ssl_certby.c:1337:1: error: ‘ngx_http_lua_ssl_verify_callback’ defined but not used [-Werror=unused-function]`

I am wondering if maybe that condition is not met when the error is being thrown? 

I did get it working - instead of the #ifdef I just deleted the definition of the function as well I deleted the other reference to that function further down. 

Sorry I had to google what "PR Welcome!" means and realized it's a pull request. I am sorry I have never done that before and I don't know how to use git. I do use Subversion hehe. 

Good news is that I can confirm that nginx compiles after this error is solved `error: ‘ngx_http_lua_ssl_verify_callback’ defined but not used [-Werror=unused-function]`  - I am sorry I have not been about to get this to work by using an ifdef check rather I had to delete the function definition and the one reference to that function doing some kind of check and BINGO! COMPILES - anyone looking for managed hosting with this feature I can shout out to my company [CloudSubnet.com](https://www.cloudsubnet.com)! 

Thank you

**Comment by Firegarden** [comment]
I tested this and yes it compiles fine with one small difference - you actually want to use `#ifndef`

eg

`#ifndef LIBRESSL_VERSION_NUMBER
static int
ngx_http_lua_ssl_verify_callback(int ok, X509_STORE_CTX *x509_store)
{
    /*
     * we never terminate handshake here and user can later use
     * $ssl_client_verify to check verification result.
     *
     * this is consistent with Nginx behavior.
     */
    return 1;
}
#endif
`

**Comment by spacewander** [comment]
Yes, I submit a PR for it: https://github.com/openresty/lua-nginx-module/pull/1894

**Comment by Firegarden** [comment]
This has become a new issue - I just tested with OpenSSL 3.0 and my friends this is not compiling with OpenSSL 3.0 

`/usr/local/src/nginx/modules/lua-nginx-module/src/ngx_http_lua_ssl_ocsp.c
/usr/local/src/nginx/modules/lua-nginx-module/src/ngx_http_lua_ssl_certby.c:1337:1: error: ‘ngx_http_lua_ssl_verify_callback’ defined but not used [-Werror=unused-function]
 1337 | ngx_http_lua_ssl_verify_callback(int ok, X509_STORE_CTX *x509_store)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:2125: objs/addon/src/ngx_http_lua_ssl_certby.o] Error 1
`
It looks like the exact same error as with LibreSSL but this time I am using OpenSSL
