### ISSUE TITLE
Fail To Build in nginx 1.9.0 mainline - version v0.9.15

### ISSUE THREAD

**Issue by teward** [openresty/lua-nginx-module#503]
Hello.

The Lua module has a fail-to-build error in 1.9.x, at least when part of the Debian packaging from Debian's git head (which is using v0.9.15 of the Lua module according to its version lists).

The full package build test log is here: https://gist.github.com/teward/b6960f5dd0d7b202ac40

Relevant sections are this, as this is the only "error" I could find (excerpt from here to where the errors and "Process failed" lines happen - https://gist.github.com/teward/b6960f5dd0d7b202ac40#file-build-fail-amd64-2015-04-28-L4069):

    -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,-E -lpthread -lcrypt -lpam -lexpat -L/usr/lib -lm -lluajit-5.1 -lpcre -lssl -lcrypto -ldl -lz -lxml2 -lxslt -lexslt -lgd -lGeoIP \
    -Wl,-E -fstack-protector -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu/perl/5.20/CORE -lperl -ldl -lm -lpthread -lc -lcrypt
    objs/addon/src/ngx_http_lua_initworkerby.o: In function `ngx_http_lua_init_worker':
    /«PKGBUILDDIR»/debian/modules/nginx-lua/src/ngx_http_lua_initworkerby.c:230: undefined reference to `ngx_http_set_connection_log'
    objs/addon/src/ngx_http_lua_timer.o: In function `ngx_http_lua_timer_handler':
    /«PKGBUILDDIR»/debian/modules/nginx-lua/src/ngx_http_lua_timer.c:353: undefined reference to `ngx_http_set_connection_log'
    collect2: error: ld returned 1 exit status
    make[3]: *** [objs/nginx] Error 1
    objs/Makefile:364: recipe for target 'objs/nginx' failed

This module version builds fine against nginx 1.8.0 (the latest stable).

**Comment by blablacio** [comment]
Oh my, there are already like 4 issues about this. Take a look at #499, #500, #501, #502.

**Comment by teward** [comment]
Missed that, thanks.

Dupe of #500
