### ISSUE TITLE
Build with Nginx 1.12.0 and Openssl1.1.0f Failed.

### ISSUE THREAD

**Issue by FqqCS** [openresty/lua-nginx-module#1087]
Compile error:
/home/xxx/nginx/modules/lua-nginx-module-0.10.9rc5/src/ngx_http_lua_module.c: In function ‘ngx_http_lua_merge_srv_conf’:
/home/xxx/nginx/modules/lua-nginx-module-0.10.9rc5/src/ngx_http_lua_module.c:1022:37: error: passing argument 2 of ‘SSL_CTX_sess_set_get_cb’ from incompatible pointer type [-Werror]
                                     ngx_http_lua_ssl_sess_fetch_handler);
                                     ^
In file included from src/event/ngx_event_openssl.h:15:0,
                 from src/core/ngx_core.h:82,
                 from /home/xxx/nginx/modules/lua-nginx-module-0.10.9rc5/src/ddebug.h:13,
                 from /home/xxx/nginx/modules/lua-nginx-module-0.10.9rc5/src/ngx_http_lua_module.c:11:
/openssl-OpenSSL_1_1_0f/.openssl/include/openssl/ssl.h:637:6: note: expected ‘struct SSL_SESSION * (*)(struct ssl_st *, const unsigned char *, int,  int *)’ but argument is of type ‘struct SSL_SESSION * (*)(struct SSL *, u_char *, int,  int *)’
 void SSL_CTX_sess_set_get_cb(SSL_CTX *ctx,
      ^
cc1: all warnings being treated as errors

Nginx:1.12.0
lua-nginx-module:lua-nginx-module-0.10.9rc5
openssl:openssl-OpenSSL_1_1_0f

**Comment by FqqCS** [comment]
@agentzh  
Obviously, you guys are in compatible with openssl 1.1.x, may openssl 1.1.1 is going to be released, may I ask you a scheduled plan of compatible with openssl 1.1.x? will you guys just skip compatible with openssl 1.1.0 and choose compatible with openssl 1.1.1 instead ?

**Comment by FqqCS** [comment]
@ghedo @chipitsine @ctrochalakis

**Comment by agentzh** [comment]
@FqqCS See the discussions in #922 and #761. It still needs work. OpenSSL's older series are still updating, like the 1.0.2 series. So there's no rush here at all.

**Comment by agentzh** [comment]
@FqqCS OpenSSL makes many incompatible API changes. That's why it needs a lot of work on our side.

**Comment by agentzh** [comment]
This issue is duplicate with existing issues and pull requests.
