### ISSUE TITLE
Could not be compiled when upgrade openssl to 1.1.0c

### ISSUE THREAD

**Issue by kn007** [openresty/lua-nginx-module#965]
```
/data/src/lua-nginx-module/src/ngx_http_lua_module.c: In function  ngx_http_lua_merge_srv_conf :
/data/src/lua-nginx-module/src/ngx_http_lua_module.c:1017:37: error: passing argument 2 of  SSL_CTX_sess_set_get_cb  from incompatible pointer type [-Werror]
                                     ngx_http_lua_ssl_sess_fetch_handler);
                                     ^
In file included from src/event/ngx_event_openssl.h:15:0,
                 from src/core/ngx_core.h:82,
                 from /data/src/lua-nginx-module/src/ddebug.h:13,
                 from /data/src/lua-nginx-module/src/ngx_http_lua_module.c:11:
/usr/include/openssl/ssl.h:618:6: note: expected  struct SSL_SESSION * (*)(struct ssl_st *, const unsigned char *, int,  int *)  but argument is of type  struc
t SSL_SESSION * (*)(struct SSL *, u_char *, int,  int *)’
 void SSL_CTX_sess_set_get_cb(SSL_CTX *ctx,
      ^

gcc -c -I/usr/local/include/luajit-2.1  -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -DTCP_FASTOPEN=23
 -ffast-math -mtune=native -O3 -Wno-deprecated-declarations -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /data/src/ngx_devel_
kit/objs -I objs/addon/ndk -I /data/src/lua-nginx-module/src/api -I /data/src/pcre-8.40 -I objs -I src/http -I src/http/modules -I src/http/v2 -I src/http -I /
data/src/ngx_brotli/deps/brotli/include -I /data/src/ngx_devel_kit/src -I /data/src/ngx_devel_kit/src -I /data/src/ngx_devel_kit/objs -I objs/addon/ndk -I /usr
/local/include/luajit-2.1 -I src/stream \
                -o objs/addon/src/ngx_http_lua_contentby.o \
                /data/src/lua-nginx-module/src/ngx_http_lua_contentby.c
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/src/ngx_http_lua_module.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/data/src/nginx-1.11.8'
make: *** [build] Error 2
```

using 1.0.2j, it's working.

**Comment by agentzh** [comment]
@kn007 This is a duplicate ticket, there is already tickets as well as pending pull requests being reviewed. Please check them out. OpenSSL 1.1 breaks API backward compatibility so it needs much more work on our side.
